Load data sets and tools


In [15]:
#import dataset
import pandas as pd



In [16]:
df = pd.read_csv(r'D:\tharu\My Projects\Medicine recommendation system\MRS\Datasets\Training.csv')
df.head()

itching  skin_rash  nodal_skin_eruptions  continuous_sneezing  shivering  \
0        1          1                     1                    0          0   
1        0          1                     1                    0          0   
2        1          0                     1                    0          0   
3        1          1                     0                    0          0   
4        1          1                     1                    0          0   

   chills  joint_pain  stomach_pain  acidity  ulcers_on_tongue  ...  \
0       0           0             0        0                 0  ...   
1       0           0             0        0                 0  ...   
2       0           0             0        0                 0  ...   
3       0           0             0        0                 0  ...   
4       0           0             0        0                 0  ...   

   blackheads  scurring  skin_peeling  silver_like_dusting  \
0           0         0             0                    0   
1           0         0             0                    0   
2           0         0             0                    0   
3           0         0             0                    0   
4           0         0             0                    0   

   small_dents_in_nails  inflammatory_nails  blister  red_sore_around_nose  \
0                     0                   0        0                     0   
1                     0                   0        0                     0   
2                     0                   0        0                     0   
3                     0                   0        0                     0   
4                     0                   0        0                     0   

   yellow_crust_ooze         prognosis  
0                  0  Fungal infection  
1                  0  Fungal infection  
2                  0  Fungal infection  
3                  0  Fungal infection  
4                  0  Fungal infection  

[5 rows x 133 columns]

In [17]:
df.shape

(4920, 133)

In [18]:
#select prognosis column in dataframe and count inoque values in it
len(df['prognosis'].unique())

41

In [19]:
#Returns an array of all unique values in that column (removes duplicates).
df['prognosis'].unique()

array(['Fungal infection', 'Allergy', 'GERD', 'Chronic cholestasis',
       'Drug Reaction', 'Peptic ulcer diseae', 'AIDS', 'Diabetes ',
       'Gastroenteritis', 'Bronchial Asthma', 'Hypertension ', 'Migraine',
       'Cervical spondylosis', 'Paralysis (brain hemorrhage)', 'Jaundice',
       'Malaria', 'Chicken pox', 'Dengue', 'Typhoid', 'hepatitis A',
       'Hepatitis B', 'Hepatitis C', 'Hepatitis D', 'Hepatitis E',
       'Alcoholic hepatitis', 'Tuberculosis', 'Common Cold', 'Pneumonia',
       'Dimorphic hemmorhoids(piles)', 'Heart attack', 'Varicose veins',
       'Hypothyroidism', 'Hyperthyroidism', 'Hypoglycemia',
       'Osteoarthristis', 'Arthritis',
       '(vertigo) Paroymsal  Positional Vertigo', 'Acne',
       'Urinary tract infection', 'Psoriasis', 'Impetigo'], dtype=object)

Train test split


In [20]:
#train test split
from sklearn.model_selection import train_test_split

from sklearn.preprocessing import LabelEncoder



In [21]:
X = df.drop('prognosis', axis=1)
y = df['prognosis']

In [22]:
le = LabelEncoder()
le.fit(y)
Y = le.fit_transform(y)

In [23]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=20)

print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)


(3444, 132) (1476, 132) (3444,) (1476,)


Traning top models


In [10]:
from sklearn.datasets import make_classification
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier,GradientBoostingClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import MultinomialNB

from sklearn.metrics import accuracy_score,confusion_matrix
import numpy as np

#create a dictionary to store models
models ={
  "SVC":SVC(kernel='linear'),
  "RandomForestClassifier":RandomForestClassifier(n_estimators=100, random_state=42),
  "GradientBoosting":GradientBoostingClassifier(n_estimators=100, random_state=42),
  "KNeighbors":KNeighborsClassifier(n_neighbors=5),
  "MultinomialNB":MultinomialNB()
}

for model_name,model in models.items():
    #train model
    model.fit(X_train,y_train)  

    #test model
    predictions = model.predict(X_test)

    #calculate accuracy
    accuracy = accuracy_score(y_test,predictions)

    #calculate confusion matrix
    cm = confusion = confusion_matrix(y_test,predictions)

    print(f"{model_name} has accuracy of {accuracy}")
    print(f"{model_name} has confusion matrix of {cm}")
    print(np.array2string(cm, separator=', '))
   

SVC has accuracy of 1.0
SVC has confusion matrix of [[40  0  0 ...  0  0  0]
 [ 0 43  0 ...  0  0  0]
 [ 0  0 28 ...  0  0  0]
 ...
 [ 0  0  0 ... 34  0  0]
 [ 0  0  0 ...  0 41  0]
 [ 0  0  0 ...  0  0 31]]
[[40,  0,  0, ...,  0,  0,  0],
 [ 0, 43,  0, ...,  0,  0,  0],
 [ 0,  0, 28, ...,  0,  0,  0],
 ...,
 [ 0,  0,  0, ..., 34,  0,  0],
 [ 0,  0,  0, ...,  0, 41,  0],
 [ 0,  0,  0, ...,  0,  0, 31]]
RandomForestClassifier has accuracy of 1.0
RandomForestClassifier has confusion matrix of [[40  0  0 ...  0  0  0]
 [ 0 43  0 ...  0  0  0]
 [ 0  0 28 ...  0  0  0]
 ...
 [ 0  0  0 ... 34  0  0]
 [ 0  0  0 ...  0 41  0]
 [ 0  0  0 ...  0  0 31]]
[[40,  0,  0, ...,  0,  0,  0],
 [ 0, 43,  0, ...,  0,  0,  0],
 [ 0,  0, 28, ...,  0,  0,  0],
 ...,
 [ 0,  0,  0, ..., 34,  0,  0],
 [ 0,  0,  0, ...,  0, 41,  0],
 [ 0,  0,  0, ...,  0,  0, 31]]
GradientBoosting has accuracy of 1.0
GradientBoosting has confusion matrix of [[40  0  0 ...  0  0  0]
 [ 0 43  0 ...  0  0  0]
 [ 0  0 28 ...  0  0  

Single prediction

In [24]:
svc = SVC(kernel='linear')
svc.fit(X_train,y_train)
ypred = svc.predict(X_test)
accuracy_score(y_test,ypred)

1.0

Recommendation System and Prediction


load databse and use logic for recommendations 

In [25]:
import os
print(os.path.exists('model/svc.pkl'))  # Should return True if the file exists


False


In [26]:
import os
import pickle
from sklearn.svm import SVC

# Define the model directory and file path
model_dir = "model"
file_path = os.path.join(model_dir, "svc.pkl")

# Ensure the 'model' directory exists before saving the file
if not os.path.exists(model_dir):
    print("⚠️ 'model' directory not found. Creating it now...")
    os.makedirs(model_dir)

# Train an SVM model
svc = SVC(kernel="linear")

# Save the trained model using pickle
with open(file_path, "wb") as f:
    pickle.dump(svc, f)

print(f"✅ Model saved successfully at {file_path}")





⚠️ 'model' directory not found. Creating it now...
✅ Model saved successfully at model\svc.pkl


In [29]:
import os
import pickle

file_path = r"D:\tharu\My Projects\Medicine recommendation system\MRS\model\svc.pkl"

# Check if the file exists
if os.path.exists(file_path):
    with open(file_path, "rb") as f:
        svc = pickle.load(f)
    print("✅ Model loaded successfully!")
else:
    print(f"⚠️ Error: '{file_path}' not found! Train and save the model first.")


✅ Model loaded successfully!


In [30]:
X_test

itching  skin_rash  nodal_skin_eruptions  continuous_sneezing  \
4037        0          0                     0                    0   
4191        0          0                     0                    0   
432         0          0                     0                    0   
1266        1          0                     0                    0   
3765        0          0                     0                    0   
...       ...        ...                   ...                  ...   
2837        0          0                     0                    0   
2327        0          0                     0                    0   
1399        1          1                     0                    0   
1906        0          0                     0                    1   
4474        0          0                     0                    0   

      shivering  chills  joint_pain  stomach_pain  acidity  ulcers_on_tongue  \
4037          0       0           1             0        0                 0   
4191          0       0           0             0        0                 0   
432           0       0           0             1        1                 0   
1266          0       0           0             0        0                 0   
3765          0       0           1             0        0                 0   
...         ...     ...         ...           ...      ...               ...   
2837          0       0           0             0        0                 0   
2327          0       1           0             0        0                 0   
1399          0       0           0             0        0                 0   
1906          0       1           0             0        0                 0   
4474          0       0           0             0        0                 0   

      ...  pus_filled_pimples  blackheads  scurring  skin_peeling  \
4037  ...                   0           0         0             0   
4191  ...                   0           0         0             0   
432   ...                   0           0         0             0   
1266  ...                   0           0         0             0   
3765  ...                   0           0         0             0   
...   ...                 ...         ...       ...           ...   
2837  ...                   0           0         0             0   
2327  ...                   0           0         0             0   
1399  ...                   0           0         0             0   
1906  ...                   0           0         0             0   
4474  ...                   0           0         0             0   

      silver_like_dusting  small_dents_in_nails  inflammatory_nails  blister  \
4037                    0                     0                   0        0   
4191                    0                     0                   0        0   
432                     0                     0                   0        0   
1266                    0                     0                   0        0   
3765                    0                     0                   0        0   
...                   ...                   ...                 ...      ...   
2837                    0                     0                   0        0   
2327                    0                     0                   0        0   
1399                    0                     0                   0        0   
1906                    0                     0                   0        0   
4474                    0                     0                   0        0   

      red_sore_around_nose  yellow_crust_ooze  
4037                     0                  0  
4191                     0                  0  
432                      0                  0  
1266                     0                  0  
3765                     0                  0  
...                    ...                ...  
2837                     0                  0  
2327              

In [32]:
X_test.iloc[0].values

array([0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

In [35]:
svc.predict(X_test.iloc[0].values.reshape(1,-1))

NotFittedError: This SVC instance is not fitted yet. Call 'fit' with appropriate arguments before using this estimator.

In [17]:
# svc.predict(X_test.iloc[0].values.reshape(1,-1))
svc.fit(X_train, y_train)


SVC(kernel='linear')

In [18]:
svc.predict(X_test.iloc[0].values.reshape(1, -1))


c:\Users\ASUS\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(


array(['hepatitis A'], dtype=object)

In [ ]:
import pickle
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_iris

# Load dataset (example: Iris dataset)
data = load_iris()
X, y = data.data, data.target

# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Initialize the model
svc = SVC(kernel='linear')

# Train the model
svc.fit(X_train, y_train)

# 🔍 Check if X_test is a NumPy array or DataFrame
print("Type of X_test:", type(X_test))

# ✅ Ensure correct indexing
if isinstance(X_test, (list, tuple)):  # If it's a list/tuple, access the first element directly
    sample = X_test[0]
elif isinstance(X_test, np.ndarray):   # If it's a NumPy array
    sample = X_test[0].reshape(1, -1)
else:  # If it's a Pandas DataFrame
    sample = X_test.iloc[[0]]  # Double brackets ensure it's 2D

# Predict the first sample
prediction = svc.predict(sample)

# Print results
print("✅ Prediction:", prediction)
print("✅ Actual:", y_test[0])




Type of X_test: <class 'numpy.ndarray'>
✅ Prediction: [1]
✅ Actual: 1
